### ISSUE TITLE
[BUG]Custom Recipe Doesnt work with Custom ITEM [NEED URGENT FIX] 

### ISSUE THREAD

**Issue by DrugAddict420** [Steel-Dev/Monstrorvm#4]
Custom Recipe doesnt work with custom tools: 
```


[00:41:37 INFO]: [Monstrorvm] Enabling Monstrorvm v1.0.9
[00:41:37 INFO]: [Monstrorvm] Loading NBT-API...
[00:41:37 INFO]: [Monstrorvm] [NBTAPI] Found Spigot: v1_17_R1! Trying to find NMS support
[00:41:37 INFO]: [Monstrorvm] [NBTAPI] NMS support 'MC1_17_R1' loaded!
[00:41:37 INFO]: [Monstrorvm] [NBTAPI] Found Gson: class com.google.gson.Gson
[00:41:37 INFO]: [Monstrorvm] Successfully loaded NBT-API!
[00:41:37 INFO]: [Monstrorvm] Loading custom enchantments from plugins/Monstrorvm/customthings/enchantments
[00:41:37 INFO]: [Monstrorvm] Successfully loaded 1 Custom Enchants! Registering them now. (Skipping disabled)
[00:41:37 INFO]: [Monstrorvm] Registering epicitem
[00:41:37 INFO]: [Monstrorvm] Custom item monstrorvm:epicitem_book has been registered.
[00:41:37 INFO]: [Monstrorvm] Custom enchant monstrorvm:epicitem has been registered.
[00:41:37 INFO]: [Monstrorvm] Loading custom items from plugins/Monstrorvm/customthings/items
[00:41:37 INFO]: [Monstrorvm] Successfully loaded 21 Custom Items! Registering them now. (Skipping disabled)
[00:41:37 INFO]: [Monstrorvm] Registering SheeshPower.yml
[00:41:37 INFO]: [Monstrorvm] Custom item monstrorvm:SheeshPower has been registered.
[00:41:37 INFO]: [Monstrorvm] Registering OnePiece.yml
[00:41:37 INFO]: [Monstrorvm] Custom item monstrorvm:OnePiece has been registered.
[00:41:37 INFO]: [Monstrorvm] Registering RandomSoul.yml
[00:41:37 INFO]: [Monstrorvm] Custom item monstrorvm:RandomSoul has been registered.
[00:41:37 INFO]: [Monstrorvm] Registering Zangetsu.yml
[00:41:37 INFO]: [Monstrorvm] Custom item monstrorvm:Zangetsu has been registered.
[00:41:37 INFO]: [Monstrorvm] Registering ZAN.yml
[00:41:37 INFO]: [Monstrorvm] Custom item monstrorvm:Zan has been registered.
[00:41:37 INFO]: [Monstrorvm] Registering DivineShard.yml
[00:41:37 INFO]: [Monstrorvm] Custom item monstrorvm:DivineShard has been registered.
[00:41:37 INFO]: [Monstrorvm] Registering BlackShard.yml
[00:41:37 INFO]: [Monstrorvm] Custom item monstrorvm:BlackShard has been registered.
[00:41:37 INFO]: [Monstrorvm] Registering HardcoreShard.yml
[00:41:37 INFO]: [Monstrorvm] Custom item monstrorvm:HardcoreShard has been registered.
[00:41:37 INFO]: [Monstrorvm] Registering Chromium.yml
[00:41:37 INFO]: [Monstrorvm] Custom item monstrorvm:Chromium has been registered.
[00:41:37 INFO]: [Monstrorvm] Registering ExtraterrestialChromium.yml
[00:41:37 INFO]: [Monstrorvm] Custom item monstrorvm:extraterrestrialChromium has been registered.
[00:41:37 INFO]: [Monstrorvm] Registering Elucidator.yml
[00:41:37 INFO]: [Monstrorvm] Custom item monstrorvm:Elucidator has been registered.
[00:41:38 INFO]: [Monstrorvm] Registering DarkRepulser.yml
[00:41:38 INFO]: [Monstrorvm] Custom item monstrorvm:DarkRepulser has been registered.
[00:41:38 INFO]: [Monstrorvm] Registering ichigosoul.yml
[00:41:38 INFO]: [Monstrorvm] Custom item monstrorvm:IchigoSoul has been registered.
[00:41:38 INFO]: [Monstrorvm] Registering JesusSoul.yml
[00:41:38 INFO]: [Monstrorvm] Custom item monstrorvm:JesusSoul has been registered.
[00:41:38 INFO]: [Monstrorvm] Registering CursedSword.yml
[00:41:38 INFO]: [Monstrorvm] Custom item monstrorvm:CursedSword has been registered.
[00:41:38 INFO]: [Monstrorvm] Registering kiritosoul.yml
[00:41:38 INFO]: [Monstrorvm] Custom item monstrorvm:KiritoSoul has been registered.
[00:41:38 INFO]: [Monstrorvm] Registering DragonSlayer.yml
[00:41:38 INFO]: [Monstrorvm] Custom item monstrorvm:DragonSlayer has been registered.
[00:41:38 INFO]: [Monstrorvm] Registering ItalianShard.yml
[00:41:38 INFO]: [Monstrorvm] Custom item monstrorvm:ItalianShard has been registered.
[00:41:38 INFO]: [Monstrorvm] Registering blackmatter.yml
[00:41:38 INFO]: [Monstrorvm] Custom item monstrorvm:BlackMatter has been registered.
[00:41:38 INFO]: [Monstrorvm] Registering QuincySoul.yml
[00:41:38 INFO]: [Monstrorvm] Custom item monstrorvm:QuincySoul has been registered.
[00:41:38 INFO]: [Monstrorvm] Registering dragoncoin.yml
[00:41:38 INFO]: [Monstrorvm] Custom item monstrorvm:Dragon_coin has been registered.
[00:41:38 INFO]: [Monstrorvm] Loading custom mobs from plugins/Monstrorvm/customthings/mobs
[00:41:38 INFO]: [Monstrorvm] Successfully loaded 1 Custom Mobs! Registering them now. (Skipping disabled)
[00:41:38 INFO]: [Monstrorvm] Registering yy.yml
[00:41:38 INFO]: [Monstrorvm] Custom mob monstrorvm:example_mob has been registered.
[00:41:38 INFO]: [Monstrorvm] Loading custom recipes from plugins/Monstrorvm/customthings/recipes
[00:41:38 INFO]: [Monstrorvm] Successfully loaded 1 Custom recipes! Registering them now. (Skipping disabled)
[00:41:38 INFO]: [Monstrorvm] Registering hash.yml
[00:41:38 INFO]: [Monstrorvm] [ERROR] The IngredientItem MONSTRORVM:ITALIANSHARD is invalid! Error occured in: hash.yml
[00:41:38 ERROR]: Error occurred while enabling Monstrorvm v1.0.9 (Is it up to date?)
java.lang.NullPointerException: ItemStack can't be null/Air!
        at com.github.steeldev.monstrorvm.api.NBT.NBTItem.<init>(NBTItem.java:42) ~[Monstrorvm-1.0.9.jar:?]
        at com.github.steeldev.monstrorvm.api.NBT.NBTItem.<init>(NBTItem.java:28) ~[Monstrorvm-1.0.9.jar:?]
        at com.github.steeldev.monstrorvm.api.items.ItemManager.isMVItem(ItemManager.java:136) ~[Monstrorvm-1.0.9.jar:?]
        at com.github.steeldev.monstrorvm.managers.PluginRecipeManager.registerCustomRecipeYamls(PluginRecipeManager.java:231) ~[Monstrorvm-1.0.9.jar:?]
        at com.github.steeldev.monstrorvm.Monstrorvm.onEnable(Monstrorvm.java:77) ~[Monstrorvm-1.0.9.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Purpur-1329]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1329]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1329]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Purpur-1329]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Purpur-1329]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:712) ~[patched_1.17.1.jar:git-Purpur-1329]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Purpur-1329]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[patched_1.17.1.jar:git-Purpur-1329]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1329]
        at java.lang.Thread.run(Unknown Source) [?:?]
[00:41:38 INFO]: [Monstrorvm] Disabling Monstrorvm v1.0.9
[00:41:38 INFO]: [Monstrorvm] Successfully disabled!







```
As you can see i have the item italian shard but doesnt work. i already try to do 
mv, Monstrorvm prefix nothig work.

The recipe: 
```

Key: 'example_recipe_shaped'
Type: CRAFTING_SHAPED
ResultItem: COAL
ResultAmount: 10
Pattern:
  - 'WSW'
  - 'WSW'
  - 'WEW'
Ingredients:
  W: 'monstrorvm:ItalianShard'
  S: 'monstrorvm:extraterrestrialChromium'
  E: 'monstrorvm:SheeshPower'
```

**Comment by DrugAddict420** [comment]
Just to make clear, i already try with 'mv:ItalianShard' Doesnt work either

**Comment by Steel-Dev** [comment]
huh, strange, I'll get right on that!

**Comment by Steel-Dev** [comment]
I'm unable to recreate this, can you provide the yml for the ItalianShard?

**Comment by DrugAddict420** [comment]
`Key: 'ItalianShard'
BaseItem: bone_meal
DisplayName: '&eItalian Shard'
Color: '#f00505'
Lore:
  - '&dYou can use it to forge &4Epic &dor &6Legendary &dequip.'
UseEffect:
  ConsumeOnUse: true
EnchantInfo:
  mv-epicitem:
    Level: 1
    
UseEffect:
  EffectType: EFFECT_HOLDER
  PotionEffects:
    REGENERATION:
      Amplifier: 0
      Duration: 0
      Chance: 0
  ConsumeOnUse: False    `

**Comment by Steel-Dev** [comment]
huh, everything looks fine there.. one moment.

**Comment by DrugAddict420** [comment]
```
AureliumMobs
1 day ago
AureliumSkills
about 19 hours ago
Back
2 days ago
bStats
Aug 12th, 2021 4:04AM
ChatColor2
Aug 12th, 2021 6:05AM
CoinsAPI
Aug 12th, 2021 6:41AM
Essentials
1 day ago
EssentialsGeoIP
1 day ago
EssentialsXMPP
1 day ago
Monstrorvm
2 days ago
PlugMan
about 22 hours ago
Shopkeepers
1 day ago
Vault
1 day ago
VotingPlugin
about 1 hour ago
WorldEdit
Aug 12th, 2021 5:43AM

```

This are the plugins on my server let me know if some plugin need to be remove

**Comment by Steel-Dev** [comment]
That looks fine - I was able to recreate the issue by using ItalianShard as an items key, for some reason the recipe system doesnt like it.. have you tried a different key?

**Comment by DrugAddict420** [comment]
let me try it now and give you a feedback

**Comment by Steel-Dev** [comment]
Thanks.

**Comment by DrugAddict420** [comment]
yes the problem is in having chosen uppercase and lowercase characters in the same phrase / variable. It is recommended to specify to use only lowercase letters in the key variable to avoid errors.

Thanks for your super fast support! You are magical!!

**Comment by Steel-Dev** [comment]
Oh, interesting, I coulda sworn I made it not matter how the keys are typed, but you're very welcome, I will update the wiki to let people know not to use uppercase keys.
